name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 3 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install MPI
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenmpi-dev
          sudo apt-get clean
      - name: Cache venv
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-venv-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m venv ~/.venv
          ~/.venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
          pip install -r requirements-torchdep.txt
      - name: Run pytest
        run: |
          ~/.venv/bin/activate
          pytest
          mpirun -n 1 python -m pytest --with-mpi
          mpirun -n 2 python -m pytest --with-mpi
      - name: Format black
        run: |
          ~/.venv/bin/activate
          black .
          git diff --exit-code
